### ISSUE TITLE
Cursor size not changing for some values

### ISSUE THREAD

**Issue by mpauper** [phisch/phinger-cursors#2]
Hello great set of cursors, thanks!

I am using `gsettings set org.gnome.desktop.interface cursor-size <size>` to change the size of the cursor, but it seems to me that there is no difference between 24-32 and between 48-64.

Any ideas?

**Comment by nytouu** [comment]
hi,
i'm changing settings via xrdb and modifying my gtk3.0 and 4.0 settings.ini and i have the exact same issue where when the cursor size is set between 24 and 32 it will just show the 24px cursor

**Comment by phisch** [comment]
I am incredibly sorry for that. The Figma API started exporting larger bounds than necessary. I updated the build system to force correct bounds, and created a new release.

This is fixed in commit 09e66bbe713d9cefbb38b170c770a6eb0b5566bb.

Please update to the latest release: https://github.com/phisch/phinger-cursors/releases/tag/v1.1

Let me know if you encounter any other issues!

**Comment by mpauper** [comment]
No worries, thanks for fixing it so quickly!
