### ISSUE TITLE
When opening an application the cursor load the system default cursor animation

### ISSUE THREAD

**Issue by Relwi** [phisch/phinger-cursors#5]
When opening an application instead of loading this theme cursor, it loads the default cursor, here is a gif example.

![gif](https://user-images.githubusercontent.com/31081245/151600492-813257db-bf9f-4fe0-8820-3e3254c5d640.gif)

**Comment by phisch** [comment]
Which desktop environment do you run?

**Comment by Relwi** [comment]
I'm using XFCE in Arch Linux, and I don't understand what is the difference between an icon on my desktop and an app launcher, I think it is a launcher, it has a .desktop extension.
![Screenshot_2022-01-29_12-21-59](https://user-images.githubusercontent.com/31081245/151659037-a83e1b1c-d73d-48b6-b875-33b1bb5c3501.png)


<details>
    <summary>cat ~/.icons/default/index.theme</summary>
    
    `cat: /home/relwi/.icons/default/index.theme: No such file or directory`
</details>

<details>
    <summary>cat ~/.config/gtk-3.0/settings.ini</summary>
    
    `cat: /home/relwi/.config/gtk-3.0/settings.ini: No such file or directory`
</details>

**Comment by phisch** [comment]
It is very odd that this only happens with some icons.

If anyone knows which cursor name they are using there, please let me know, and ideally link to their code so I can check for any other missing ones in there. I looked through their repository mirrors on GitHub but did not find any cursor names that are missing in phinger cursors.

I'll setup a test XFCE desktop to debug this eventually if nobody can help.

**Comment by Relwi** [comment]
It is not such a big problem so take it easy. Here I create some other gifs:
<details>
<summary>Phinger Cursors</summary>

![Peek 2022-01-30 09-59](https://user-images.githubusercontent.com/31081245/151693711-6fea2fcb-8c25-4a49-8805-0f630f3ea026.gif)

![Peek 2022-01-30 10-01](https://user-images.githubusercontent.com/31081245/151693741-c2d3f24d-ef74-4ab2-a2e0-954ebb3b9c2f.gif)
</details>

I tried other cursor theme and this problem doesn't happen. [Nordzy-cursors](https://github.com/alvatip/Nordzy-cursors)
<details>
<summary>Nordzy Cursors</summary>

![Peek 2022-01-30 10-05](https://user-images.githubusercontent.com/31081245/151693824-a62b5b62-3e5d-44b4-b789-fab575de289c.gif)

![Peek 2022-01-30 10-07](https://user-images.githubusercontent.com/31081245/151693826-a3606479-5ada-4604-ae38-bcd3e9042963.gif)
</details>

**Comment by Francicoria** [comment]
Edit ~/.config/gtk-3.0/settings.ini (user-only) or /usr/share/gtk-3.0/settings.ini (system-wide) and add the line 
`gtk-cursor-theme-name=phinger-cursors`
and edit .icons/default/index.theme (user-only) or /usr/share/icons/default/index.theme (system-wide) and at the line starting with `Inherits=` instead of `Adwaita` put `phinger-cursors`

**Comment by Relwi** [comment]
I have this one:
![Peek 2022-02-06 11-44](https://user-images.githubusercontent.com/31081245/152677174-550b9072-d9b7-4073-a9e8-06fec7dd12c2.gif)

**Comment by phisch** [comment]
Don't bother, I'll fix this eventually for the next release. I am just a little busy right now.

**Comment by phisch** [comment]
Hey @Relwi sorry for the long wait. But I finally managed to get the new build system done and published the [2.0-beta.1 release](https://github.com/phisch/phinger-cursors/releases/tag/v2.0-beta.1). Do you mind checking if this issue still happens with that? Gnome also cleaned up their cursor file names and aliases in one of their last releases, so that might have also fixed some things.

**Comment by Relwi** [comment]
Hi @phisch,

I'm not using xfce anymore, I tried it in sway instead. I don't see any issues at all, one thing that can say is that when opening an app with [bemenu](https://github.com/Cloudef/bemenu) the cursor doesn't change to the loading animation, but don't know if this is a cursor, composable or bemenu thing, however, this is not such a big problem I think.

Also I tried this https://nabeelgit.github.io/cursor-changer/ to test the cursor, all works fine.

The only issue that I found is that in XWayland apps the cursor changes to the default one, in my case, to the Adwaita cursor theme. I don't think this is a cursor issue but a XWayland issue or something else.

Back to this ticket issue, I think the problem is fixed, like I said, when opening an app, it doesn't change to the loading animation, but it doesn't change to the default cursor either, so is fine.

**Comment by phisch** [comment]
I tested out XFCE, and it turns out they use the name `08e8e1c95fe2fc01f976f1e063a24ccd` for this specific loading cursor. It's a bit ridiculous that some application still use those decades old hashed names.

Gonna add it for the stable release. 

Closing since this fixes the issue:
![xfce_desktop_loading](https://github.com/phisch/phinger-cursors/assets/1282767/db72e187-39be-4227-acdf-46e3345676ec)

**Comment by phisch** [comment]
@Relwi I also looked at bemenu, but couldn't figure out (in reasonable time) how they draw their cursors. So they probably just use the default then.

> The only issue that I found is that in XWayland apps the cursor changes to the default one, in my case, to the Adwaita cursor theme. I don't think this is a cursor issue but a XWayland issue or something else.

Can you either open a new Issue for one of the XWayland apps where a wrong cursor is shown, or just comment it here?

Also, thanks a lot for your help!

**Comment by Relwi** [comment]
The theme issue happens in QT apps under XWayland and Steam in my case, but in GTK apps under XWayland like Thunderbird the cursors works fine, so I think this is something related to QT, idk.
